;;; acp-tests.el --- ACP cancellation and capability tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'agent-shell-fork-tree)

(defmacro aft-test-transport (&rest body)
  (declare (indent 0))
  `(let* ((source (generate-new-buffer " *aft-transport-source*"))
          (store (agent-shell-fork-tree--new-store "fixture" "/tmp"))
          (agent-shell-fork-tree-cache-directory nil)
          requests pending cancel result finished callback client worker
          (caps '((loadSession . t) (sessionCapabilities (list) (fork) (delete))))
          (rows [((sessionId . "main") (title . "Main") (updatedAt . "1"))]))
     (unwind-protect
         (cl-letf (((symbol-function 'acp-subscribe-to-notifications)
                    (lambda (&rest args) (setq callback (plist-get args :on-notification))))
                   ((symbol-function 'acp-send-request)
                    (lambda (&rest args)
                      (setq client (plist-get args :client) worker (plist-get args :buffer))
                      (unless (map-elt client :process)
                        (setf (map-elt client :process) (make-pipe-process :name "aft-transport" :noquery t)))
                      (push (plist-get args :request) requests)
                      (with-current-buffer worker
                        (pcase (map-elt (plist-get args :request) :method)
                          ("initialize" (funcall (plist-get args :on-success) `((agentCapabilities . ,caps))))
                          ("session/list" (funcall (plist-get args :on-success) `((sessions . ,rows))))
                          ("session/delete" (funcall (plist-get args :on-success) nil))
                          (_ (setq pending args)))))))
           (with-current-buffer source
             (setq-local agent-shell--state
                         (agent-shell--make-state
                          :buffer source :agent-config `((:identifier . fixture) (:client-maker . ,(lambda (b) (acp-make-client :command "fake" :context-buffer b)))))))
           (cl-labels ((start ()
                         (setq cancel (agent-shell-fork-tree--scan source store "main" nil #'ignore
                                                                  (lambda (_store error cancelled) (setq finished t result (list error cancelled))))))
                       (reply (response &optional failure)
                         (let ((args pending))
                           (setq pending nil)
                           (with-current-buffer (plist-get args :buffer)
                             (if failure
                                 (acp--call-request-failure :client client
                                                           :incoming-response `((:buffer . ,worker) (:on-failure . ,(plist-get args :on-failure)))
                                                           :error-data response :message nil)
                               (funcall (plist-get args :on-success) response)))))
                       (updates (rows)
                         (dolist (row rows)
                           (with-current-buffer worker
                             (funcall callback `((method . "session/update") (params (sessionId . "snapshot") (update . ,row))))))))
             ,@body))
       (when client (acp-shutdown :client client))
       (when (buffer-live-p worker) (kill-buffer worker))
       (kill-buffer source))))

(ert-deftest aft-test-cancelled-fork-deletes-only-late-owned-id ()
  (aft-test-transport
    (start)
    (funcall cancel)
    (reply '((sessionId . "snapshot")))
    (should finished)
    (should (equal '(nil t) result))
    (should (equal "session/delete" (map-elt (car requests) :method)))
    (should (equal "snapshot" (map-nested-elt (car requests) '(:params sessionId))))
    (should-not (seq-find (lambda (r) (equal "session/load" (map-elt r :method))) requests))
    (should-not (buffer-live-p worker))))

(ert-deftest aft-test-cancelled-replay-persists-only-completed-turns ()
  (aft-test-transport
    (start)
    (reply '((sessionId . "snapshot")))
    (updates (aft-test-updates '("one" "unfinished")))
    (funcall cancel)
    (reply nil)
    (should (equal '(nil t) result))
    (let ((session (gethash "main" (agent-shell-fork-tree--store-sessions store))))
      (should (= 1 (length (agent-shell-fork-tree--session-path session))))
      (should (eq 'partial (agent-shell-fork-tree--session-coverage session)))
      (should (agent-shell-fork-tree--session-dirty session)))))

(ert-deftest aft-test-rpc-failure-cleans-up-and-finishes-once ()
  (aft-test-transport
    (start)
    (reply '((sessionId . "snapshot")))
    (reply '((message . "Load rejected")) t)
    (should finished)
    (should (string-match-p "Load rejected" (car result)))
    (should (equal "session/delete" (map-elt (car requests) :method)))
    (should-not (buffer-live-p worker))))

(ert-deftest aft-test-missing-required-capability-fails-before-list ()
  (aft-test-transport
    (setq caps '((loadSession . t)))
    (start)
    (should finished)
    (should (string-match-p "advertise session/list" (car result)))
    (should (= 1 (length requests)))))

(ert-deftest aft-test-no-delete-capability-does-not-create-read-forks ()
  (aft-test-transport
    (setq caps '((loadSession . t) (sessionCapabilities (list) (fork) (close))))
    (start)
    (should (equal "session/load" (map-elt (plist-get pending :request) :method)))
    (reply nil)
    (should finished)
    (should-not (seq-find (lambda (r) (equal "session/fork" (map-elt r :method))) requests))))

(ert-deftest aft-test-current-ids-replace-checkpoint-aliases ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("one") nil "old-")
    (aft-test-add store "main" '("one") "2" "new-")
    (cl-letf (((symbol-function 'agent-shell-fork-tree--fingerprint) (lambda (&rest _) (ert-fail "Rehashed refreshed checkpoint"))))
      (aft-test-add store "main" '("one") "3" "new-"))))

(ert-deftest aft-test-checkpoints-batch-and-flush-at-completion ()
  (aft-test-transport
    (setq rows [((sessionId . "main") (updatedAt . "1"))
                ((sessionId . "branch") (updatedAt . "1"))])
    (let ((agent-shell-fork-tree-checkpoint-batch-size 16) (writes 0))
      (cl-letf (((symbol-function 'agent-shell-fork-tree--save)
                 (lambda (_) (cl-incf writes))))
        (start)
        (reply '((sessionId . "snapshot")))
        (updates (aft-test-updates '("one")))
        (reply nil)
        (should (= 0 writes))
        (should (gethash "main" (agent-shell-fork-tree--store-sessions store)))
        (reply '((sessionId . "snapshot")))
        (updates (aft-test-updates '("one" "two")))
        (reply nil)
        (should finished)
        (should (= 1 writes))))))

(ert-deftest aft-test-checkpoints-flush-on-cancel-and-failure ()
  (dolist (failure '(nil t))
    (aft-test-transport
      (let* ((agent-shell-fork-tree-cache-directory (make-temp-file "aft-flush-" t))
             (agent-shell-fork-tree-checkpoint-batch-size 16))
        (unwind-protect
            (progn
              (start)
              (reply '((sessionId . "snapshot")))
              (updates (aft-test-updates '("one" "unfinished")))
              (if failure (reply '((message . "Rejected")) t)
                (funcall cancel)
                (reply nil))
              (should finished)
              (let ((fresh (agent-shell-fork-tree--load "fixture" "/tmp")))
                (should (equal '(1) (aft-test-path fresh "main")))
                (should (agent-shell-fork-tree--session-dirty
                         (gethash "main" (agent-shell-fork-tree--store-sessions fresh))))))
          (delete-directory agent-shell-fork-tree-cache-directory t))))))

(ert-deftest aft-test-checkpoint-cached-metadata ()
  (aft-test-transport
    (setq rows [((sessionId . "main") (title . "Renamed") (updatedAt . "1"))])
    (aft-test-add store "main" '("one"))
    (aft-test-add store "deleted" '("one"))
    (let ((writes 0) (revision (agent-shell-fork-tree--store-revision store)))
      (cl-letf (((symbol-function 'agent-shell-fork-tree--save)
                 (lambda (_) (cl-incf writes))))
        (start)
        (should finished)
        (should (= 1 writes))
        (should (> (agent-shell-fork-tree--store-revision store) revision))
        (should (equal "Renamed" (agent-shell-fork-tree--session-title
                                 (gethash "main" (agent-shell-fork-tree--store-sessions store)))))
        (should-not (gethash "deleted" (agent-shell-fork-tree--store-sessions store)))
        (should-not (seq-find (lambda (r) (equal "session/load" (map-elt r :method))) requests))))))

(ert-deftest aft-test-checkpoint-one-saves-every-read ()
  (aft-test-transport
    (setq rows [((sessionId . "main") (updatedAt . "1"))
                ((sessionId . "branch") (updatedAt . "1"))])
    (let ((agent-shell-fork-tree-checkpoint-batch-size 1) (writes 0))
      (cl-letf (((symbol-function 'agent-shell-fork-tree--save)
                 (lambda (_) (cl-incf writes))))
        (start)
        (reply '((sessionId . "snapshot")))
        (updates (aft-test-updates '("one")))
        (reply nil)
        (should (= 1 writes))
        (reply '((sessionId . "snapshot")))
        (updates (aft-test-updates '("one" "two")))
        (reply nil)
        (should finished)
        (should (= 2 writes))))))

(ert-deftest aft-test-cached-scan-does-not-write-or-load ()
  (aft-test-transport
    (aft-test-add store "main" '("one"))
    (setf (agent-shell-fork-tree--session-title
           (gethash "main" (agent-shell-fork-tree--store-sessions store))) "Main")
    (cl-letf (((symbol-function 'agent-shell-fork-tree--save)
               (lambda (_) (ert-fail "Unchanged cache was written"))))
      (start)
      (should finished)
      (should-not (seq-find (lambda (r) (equal "session/load" (map-elt r :method))) requests)))))

(ert-deftest aft-test-checkpoint-write-failure-still-cleans-up ()
  (aft-test-transport
    (cl-letf (((symbol-function 'agent-shell-fork-tree--save)
               (lambda (_) (error "Disk full"))))
      (start)
      (reply '((sessionId . "snapshot")))
      (updates (aft-test-updates '("one")))
      (reply nil)
      (should finished)
      (should (string-match-p "Disk full" (car result)))
      (should-not (buffer-live-p worker))
      (should (gethash "main" (agent-shell-fork-tree--store-sessions store))))))

(ert-deftest aft-test-auto-events-only-schedule-visible-related-trees ()
  (let* ((source (generate-new-buffer " *aft-auto-source*"))
         (view (generate-new-buffer " *aft-auto-tree*"))
         (store (agent-shell-fork-tree--new-store "fixture" "/tmp"))
         (agent-shell-fork-tree-auto-rebuild nil)
         timer-callback (rebuilds 0))
    (unwind-protect
        (progn
          (aft-test-add store "main" '("one"))
          (with-current-buffer source
            (setq-local agent-shell--state (agent-shell--make-state :buffer source))
            (setf (map-elt (map-elt agent-shell--state :session) :id) "main"))
          (with-current-buffer view
            (agent-shell-fork-tree-view-mode)
            (setq agent-shell-fork-tree--store store agent-shell-fork-tree--focus "main" agent-shell-fork-tree--source source))
          (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) t))
                    ((symbol-function 'shell-maker-busy) (lambda () nil))
                    ((symbol-function 'agent-shell-fork-tree-rebuild) (lambda (&rest _) (cl-incf rebuilds)))
                    ((symbol-function 'run-at-time) (lambda (_time _repeat fn &rest _) (setq timer-callback fn) nil)))
            (with-current-buffer source (agent-shell-fork-tree--event '((:event . turn-complete))))
            (should-not timer-callback)
            (setq agent-shell-fork-tree-auto-rebuild t)
            (with-current-buffer source (agent-shell-fork-tree--event '((:event . turn-complete))))
            (should timer-callback)
            (funcall timer-callback)
            (should (= 1 rebuilds))))
      (kill-buffer view) (kill-buffer source))))
