;;; integration-tests.el --- Real ACP subprocess tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'agent-shell-fork-tree)
(defconst aft-test-directory (file-name-directory (or load-file-name buffer-file-name)))
(defun aft-test-wait (predicate)
  (let ((deadline (+ (float-time) 15)))
    (while (and (not (funcall predicate)) (< (float-time) deadline)) (accept-process-output nil 0.02))
    (should (funcall predicate))))
(defun aft-test-read-store (directory)
  (with-temp-buffer (insert-file-contents (expand-file-name "store.json" directory))
                    (json-parse-buffer :object-type 'hash-table)))
(defun aft-test-load-count (directory)
  (with-temp-buffer
    (insert-file-contents (expand-file-name "requests.jsonl" directory))
    (count-matches "session/load" (point-min) (point-max))))

(defun aft-test-workflow (profile)
  (let* ((directory (directory-file-name (file-truename (make-temp-file "aft-acp-" t))))
         (default-directory (file-name-as-directory directory))
         (shell-maker-root-path directory)
         (agent-shell-fork-tree-cache-directory (expand-file-name "cache" directory))
         (agent-shell-fork-tree--stores (make-hash-table :test #'equal))
         (agent-shell-fork-tree-auto-rebuild nil)
         (agent-shell-mode-hook '(agent-shell-fork-tree-mode)) (agent-shell-session-restore-verbosity 'minimal)
         (agent-shell-show-welcome-message nil) (agent-shell-header-style nil)
         (agent-shell-show-context-usage-indicator nil) (agent-shell-show-usage-at-turn-end nil)
         (agent-shell-mcp-servers nil) (agent-shell-context-sources nil)
         (agent-shell-prefer-viewport-interaction nil) (agent-shell-chat-mode-enabled nil)
         (config (agent-shell-make-agent-config
                  :identifier 'fixture :buffer-name "ForkFixture" :mode-line-name "Fixture"
                  :shell-prompt "Fixture> " :shell-prompt-regexp "Fixture> "
                  :client-maker (lambda (buffer)
                                  (acp-make-client :command (executable-find "python3") :context-buffer buffer
                                                   :command-params (list "-u" (expand-file-name "mock_acp.py" aft-test-directory) directory profile)))))
         parent view fork resumed failed-shell store parent-id parent-text)
    (unwind-protect
        (save-window-excursion
          (with-temp-file (expand-file-name "store.json" directory)
            (insert (json-serialize
                     '((historic . ((title . "Old fork") (updated . 1)
                                    (turns . [((prompt . "alpha") (userId . "u1") (agentId . "a1"))
                                              ((prompt . "gamma") (userId . "u2") (agentId . "a2"))])))
                       (identical . ((title . "Identical") (updated . 1)
                                     (turns . [((prompt . "alpha") (userId . "copy-u1") (agentId . "copy-a1"))
                                               ((prompt . "beta") (userId . "copy-u2") (agentId . "copy-a2"))])))
                       (foreign . ((title . "Foreign session") (updated . 1)
                                   (turns . [((prompt . "unrelated") (userId . "f1") (agentId . "f2"))])))
                       (empty . ((title . "Empty") (updated . 1) (turns . [])))))))
          (setq parent (agent-shell--start :config config :no-focus t :new-session t :session-strategy 'new))
          (aft-test-wait (lambda () (with-current-buffer parent (and (map-nested-elt agent-shell--state '(:session :id)) (not (shell-maker-busy))))))
          (dolist (prompt '("alpha" "beta"))
            (with-current-buffer parent (agent-shell-insert :text prompt :submit t :no-focus t :shell-buffer parent))
            (aft-test-wait (lambda () (with-current-buffer parent (not (shell-maker-busy))))))
          (with-current-buffer parent
            (setq parent-id (map-nested-elt agent-shell--state '(:session :id)) parent-text (buffer-string))
            (agent-shell-fork-tree)
            (setq view (current-buffer)))
          (should (= 0 (aft-test-load-count directory))) ; Manual mode does not read history on open.
          (with-current-buffer view (agent-shell-fork-tree-rebuild))
          (aft-test-wait (lambda () (not (buffer-local-value 'agent-shell-fork-tree--loading view))))
          (with-current-buffer view
            (should (equal "Up to date" agent-shell-fork-tree--status))
            (setq store agent-shell-fork-tree--store)
            (should (= 3 (length (agent-shell-fork-tree--related store parent-id))))
            (should-not (string-match-p "Foreign session\\|unrelated\\|↳ Empty" (buffer-string)))
            (should (string-match-p "Old fork" (buffer-string)))
            (should (= 2 (length (aft-test-path store parent-id)))))
          (should (equal parent-text (with-current-buffer parent (buffer-string))))
          (should (= 5 (hash-table-count (aft-test-read-store directory))))
          (let ((before (aft-test-load-count directory)))
            (with-current-buffer view (agent-shell-fork-tree-rebuild))
            (aft-test-wait (lambda () (not (buffer-local-value 'agent-shell-fork-tree--loading view))))
            (should (= before (aft-test-load-count directory))))
          (with-current-buffer parent (agent-shell-insert :text "delta" :submit t :no-focus t :shell-buffer parent))
          (aft-test-wait (lambda () (with-current-buffer parent (not (shell-maker-busy)))))
          (let ((before (aft-test-load-count directory)))
            (with-current-buffer view (agent-shell-fork-tree-rebuild))
            (aft-test-wait (lambda () (not (buffer-local-value 'agent-shell-fork-tree--loading view))))
            (should (= (1+ before) (aft-test-load-count directory))))
          (should (= 3 (length (aft-test-path store parent-id))))
          ;; Continue a native endpoint and fork another on its creating client.
          (with-current-buffer view
            (setq agent-shell-fork-tree--selected-session "historic")
            (agent-shell-fork-tree-continue)
            (setq resumed (current-buffer)))
          (aft-test-wait (lambda () (with-current-buffer resumed (and (map-nested-elt agent-shell--state '(:session :id)) (not (shell-maker-busy))))))
          (should (equal "historic" (map-nested-elt (buffer-local-value 'agent-shell--state resumed) '(:session :id))))
          (with-current-buffer view
            (setq agent-shell-fork-tree--selected-session parent-id)
            (agent-shell-fork-tree-fork)
            (setq fork (current-buffer)))
          (aft-test-wait (lambda () (with-current-buffer fork (and (map-nested-elt agent-shell--state '(:session :id)) (not (shell-maker-busy))))))
          (with-current-buffer fork (agent-shell-insert :text "child" :submit t :no-focus t :shell-buffer fork))
          (aft-test-wait (lambda () (with-current-buffer fork (not (shell-maker-busy)))))
          (let* ((native (aft-test-read-store directory))
                 (child-id (map-nested-elt (buffer-local-value 'agent-shell--state fork) '(:session :id))))
            (should (= 6 (hash-table-count native)))
            (should (= 4 (length (gethash "turns" (gethash child-id native))))))
          ;; Rewritten prefix must fail incrementally, keep the old store, and ask once.
          (let ((native (aft-test-read-store directory)) (offered 0))
            (puthash "prompt" "rewritten" (aref (gethash "turns" (gethash parent-id native)) 0))
            (puthash "updated" 99 (gethash parent-id native))
            (with-temp-file (expand-file-name "store.json" directory) (insert (json-serialize native)))
            (cl-letf (((symbol-function 'agent-shell-fork-tree--offer-full)
                       (lambda (_view _error) (cl-incf offered))))
              (with-current-buffer view (agent-shell-fork-tree-rebuild))
              (aft-test-wait (lambda () (= offered 1))))
            (should (eq store (buffer-local-value 'agent-shell-fork-tree--store view)))
            (should (equal "alpha" (agent-shell-fork-tree--node-prompt (agent-shell-fork-tree--node store (car (aft-test-path store parent-id)))))))
          (with-current-buffer view (agent-shell-fork-tree-rebuild t))
          (aft-test-wait (lambda () (not (buffer-local-value 'agent-shell-fork-tree--loading view))))
          (should-not (eq store (buffer-local-value 'agent-shell-fork-tree--store view)))
          (with-current-buffer view
            (should (equal "Up to date" agent-shell-fork-tree--status))
            (should (= 1 (length (agent-shell-fork-tree--related agent-shell-fork-tree--store parent-id)))))
          ;; No silent new-session fallback when a native session disappeared.
          (with-current-buffer view
            (let ((missing (agent-shell-fork-tree--session-create :id "missing" :title "Missing" :coverage 'full)))
              (puthash "missing" missing (agent-shell-fork-tree--store-sessions agent-shell-fork-tree--store)))
            (setq agent-shell-fork-tree--selected-session "missing")
            (agent-shell-fork-tree-continue)
            (setq failed-shell (current-buffer)))
          (aft-test-wait (lambda () (with-current-buffer failed-shell (string-match-p "Unknown session" (buffer-string)))))
          (should-not (map-nested-elt (buffer-local-value 'agent-shell--state failed-shell) '(:session :id)))
          (should (= 6 (hash-table-count (aft-test-read-store directory)))))
      (when (and (buffer-live-p view) (buffer-live-p (buffer-local-value 'agent-shell-fork-tree--preview view)))
        (kill-buffer (buffer-local-value 'agent-shell-fork-tree--preview view)))
      (dolist (buffer (list view parent fork resumed failed-shell))
        (when (buffer-live-p buffer) (with-current-buffer buffer (setq-local kill-buffer-query-functions nil) (kill-buffer buffer))))
      (delete-directory directory t))))

(ert-deftest aft-test-acp-regenerated-fork-ids () (aft-test-workflow "regenerate"))
(ert-deftest aft-test-acp-direct-load-without-delete () (aft-test-workflow "direct"))
