;;; run-tests.el --- Run ERT in an existing Emacs server -*- lexical-binding: t; -*-
(require 'ert)
(let* ((directory (file-name-directory (or load-file-name buffer-file-name)))
       (root (expand-file-name ".." directory))
       (debug-on-error nil) (debug-on-quit nil))
  (add-to-list 'load-path root)
  (dolist (name '("agent-shell-fork-tree-store.el" "agent-shell-fork-tree-acp.el" "agent-shell-fork-tree.el"))
    (load (expand-file-name name root) nil t))
  (dolist (test (ert-select-tests "^aft-test-" t)) (ert-delete-test (ert-test-name test)))
  (dolist (file (directory-files directory t "-tests\\.el$"))
    (unless (equal file (expand-file-name "run-tests.el" directory)) (load file nil t)))
  (let ((stats (ert-run-tests-batch "^aft-test-")))
    (message "Fork tree: %d tests, %d unexpected" (ert-stats-total stats) (ert-stats-completed-unexpected stats))
    (when (> (ert-stats-completed-unexpected stats) 0) (error "Fork-tree tests failed"))))
