;;; store-tests.el --- Cache and prefix tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'agent-shell-fork-tree)

(defun aft-test-updates (words &optional prefix)
  (cl-loop for word in words for i from 0 append
           `(((sessionUpdate . "user_message_chunk") (messageId . ,(format "%su%d" prefix i)) (content (type . "text") (text . ,word)))
             ((sessionUpdate . "agent_message_chunk") (messageId . ,(format "%sa%d" prefix i)) (content (type . "text") (text . ,(concat "Reply: " word)))))))
(defun aft-test-add (store id words &optional version prefix complete)
  (agent-shell-fork-tree--ingest store `((sessionId . ,id) (title . ,id) (updatedAt . ,(or version "1")))
                                (agent-shell-fork-tree--turns (aft-test-updates words prefix) t)
                                (not (eq complete 'partial)) "main"))
(defun aft-test-path (store id)
  (mapcar (lambda (record) (map-elt record 'node))
          (agent-shell-fork-tree--session-path (gethash id (agent-shell-fork-tree--store-sessions store)))))

(ert-deftest aft-test-content-prefix-and-independent-endpoints ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha" "beta") nil "main-")
    (aft-test-add store "branch" '("alpha" "gamma") nil "new-")
    (aft-test-add store "identical" '("alpha" "beta") nil "copy-")
    (should (equal '(1 2) (aft-test-path store "main")))
    (should (equal '(1 3) (aft-test-path store "branch")))
    (should (equal '(1 2) (aft-test-path store "identical")))
    (should (= 4 (hash-table-count (agent-shell-fork-tree--store-nodes store))))
    (should (= 3 (length (agent-shell-fork-tree--related store "main"))))))

(ert-deftest aft-test-id-hit-does-not-hash-again ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha" "beta"))
    (cl-letf (((symbol-function 'agent-shell-fork-tree--fingerprint) (lambda (&rest _) (ert-fail "Rehashed a known ID"))))
      (aft-test-add store "copy" '("alpha" "beta")))
    (should (equal (aft-test-path store "main") (aft-test-path store "copy")))))

(ert-deftest aft-test-incremental-only-hashes-new-turns ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp"))
        (hash-function (symbol-function 'agent-shell-fork-tree--fingerprint)) hashed)
    (aft-test-add store "main" '("alpha" "beta"))
    (cl-letf (((symbol-function 'agent-shell-fork-tree--fingerprint)
               (lambda (prompt answer) (push (list prompt answer) hashed) (funcall hash-function prompt answer))))
      (aft-test-add store "main" '("alpha" "beta" "gamma") "2"))
    (should (equal '(("gamma" "Reply: gamma")) hashed))
    (should (= 3 (length (aft-test-path store "main"))))))

(ert-deftest aft-test-ids-never-override-changed-text ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha" "beta"))
    (should-error (aft-test-add store "main" '("changed" "beta") "2") :type 'agent-shell-fork-tree-incremental-error)
    (should-error (aft-test-add store "main" '("alpha") "2") :type 'agent-shell-fork-tree-incremental-error)
    (should (equal '(1 2) (aft-test-path store "main")))
    (aft-test-add store "other" '("different" "beta"))
    (should-not (= 1 (car (aft-test-path store "other"))))))

(ert-deftest aft-test-unrelated-and-empty-candidates-do-not-enter-view ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha" "beta"))
    (aft-test-add store "unrelated" '("other" "alpha" "beta") nil "other-")
    (aft-test-add store "empty" nil)
    (should (= 1 (length (aft-test-path store "unrelated")))))
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" nil)
    (aft-test-add store "empty" nil)
    (should (equal '("main") (mapcar #'agent-shell-fork-tree--session-id (agent-shell-fork-tree--related store "main"))))))

(ert-deftest aft-test-render-and-search-exclude-unrelated-paths ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha" "beta"))
    (aft-test-add store "copy" '("alpha" "beta") nil "copy-")
    (aft-test-add store "foreign" '("unrelated-prompt"))
    (with-temp-buffer
      (agent-shell-fork-tree-view-mode)
      (setq agent-shell-fork-tree--store store agent-shell-fork-tree--focus "main")
      (agent-shell-fork-tree--render)
      (should (string-match-p "↳ main" (buffer-string)))
      (should (string-match-p "↳ copy" (buffer-string)))
      (should-not (string-match-p "foreign\\|unrelated-prompt" (buffer-string)))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt choices &rest _) (should (= 3 (length choices))) (caar choices))))
        (agent-shell-fork-tree-find)))))

(ert-deftest aft-test-repeated-text-under-another-parent-stays-separate ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha" "beta" "alpha"))
    (should (= 4 (hash-table-count (agent-shell-fork-tree--store-nodes store))))
    (should-not (= (car (aft-test-path store "main")) (car (last (aft-test-path store "main")))))))

(ert-deftest aft-test-streaming-and-incomplete-checkpoint ()
  (let* ((updates '(((sessionUpdate . "user_message_chunk") (messageId . "u1") (content (text . "hel")))
                    ((sessionUpdate . "user_message_chunk") (messageId . "u1") (content (text . "lo")))
                    ((sessionUpdate . "agent_thought_chunk") (messageId . "thought") (content (text . "private reasoning")))
                    ((sessionUpdate . "agent_message_chunk") (messageId . "a1") (content (text . "O")))
                    ((sessionUpdate . "agent_message_chunk") (messageId . "a1") (content (text . "K")))
                    ((sessionUpdate . "user_message_chunk") (messageId . "u2") (content (text . "pending")))
                    ((sessionUpdate . "agent_message_chunk") (messageId . "a2") (content (text . "partial")))))
         (turns (agent-shell-fork-tree--turns updates nil)))
    (should (= 1 (length turns)))
    (should (equal "hello" (plist-get (car turns) :prompt)))
    (should (equal "OK" (plist-get (car turns) :answer)))
    (should (equal '("u1" "a1") (plist-get (car turns) :ids)))
    (should (= 2 (length (agent-shell-fork-tree--turns updates t))))))

(ert-deftest aft-test-tool-data-does-not-enter-fingerprint ()
  (let* ((store (agent-shell-fork-tree--new-store "fixture" "/tmp"))
         (updates (append (seq-take (aft-test-updates '("alpha")) 1)
                          '(((sessionUpdate . "tool_call") (toolCallId . "one") (title . "First")
                             (content . [((type . "diff") (path . "file") (oldText . "old") (newText . "new"))]))
                            ((sessionUpdate . "tool_call") (toolCallId . "two") (title . "Second")))
                          (cdr (aft-test-updates '("alpha"))))))
    (aft-test-add store "main" '("alpha"))
    (agent-shell-fork-tree--ingest store '((sessionId . "tools") (updatedAt . "1")) (agent-shell-fork-tree--turns updates t) t "main")
    (should (equal '(1) (aft-test-path store "tools")))
    (let ((tools (plist-get (car (agent-shell-fork-tree--turns updates t)) :tools)))
      (should (equal '("First" "Second") (mapcar (lambda (tool) (map-elt (cdr tool) 'title)) tools))))))

(ert-deftest aft-test-cache-roundtrip-preserves-aliases-labels-and-progress ()
  (let* ((agent-shell-fork-tree-cache-directory (make-temp-file "aft-cache-" t))
         (store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (unwind-protect
        (progn
          (aft-test-add store "main" '("alpha" "beta") nil "main-")
          (aft-test-add store "branch" '("alpha" "gamma") nil "other-" 'partial)
          (setf (agent-shell-fork-tree--node-label (agent-shell-fork-tree--node store 1)) "Start")
          (agent-shell-fork-tree--save store)
          (let ((fresh (agent-shell-fork-tree--load "fixture" "/tmp")))
            (should (equal '(1 3) (aft-test-path fresh "branch")))
            (should (agent-shell-fork-tree--session-dirty (gethash "branch" (agent-shell-fork-tree--store-sessions fresh))))
            (should (equal "Start" (agent-shell-fork-tree--node-label (agent-shell-fork-tree--node fresh 1))))
            (cl-letf (((symbol-function 'agent-shell-fork-tree--fingerprint) (lambda (&rest _) (ert-fail "Lost ID aliases"))))
              (aft-test-add fresh "copy" '("alpha" "gamma") nil "other-")))
          (should (= #o600 (logand #o777 (file-modes (car (directory-files agent-shell-fork-tree-cache-directory t "\\.json$")))))))
      (delete-directory agent-shell-fork-tree-cache-directory t))))

(ert-deftest aft-test-unchanged-and-negative-cache-skip-reads ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha"))
    (aft-test-add store "foreign" '("other"))
    (should-not (agent-shell-fork-tree--needs-read store '((sessionId . "main") (updatedAt . "1")) "main" nil))
    (should-not (agent-shell-fork-tree--needs-read store '((sessionId . "foreign") (updatedAt . "1")) "main" nil))
    (should (agent-shell-fork-tree--needs-read store '((sessionId . "foreign") (updatedAt . "1")) "foreign" nil))
    (should (agent-shell-fork-tree--needs-read store '((sessionId . "main") (updatedAt . "2")) "main" nil))
    (should (agent-shell-fork-tree--needs-read store '((sessionId . "main")) "main" nil))))

(ert-deftest aft-test-no-ids-or-reassigned-ids-use-text ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" '("alpha" "beta"))
    (let ((turns (agent-shell-fork-tree--turns (aft-test-updates '("alpha" "beta")) t)))
      (dolist (turn turns) (plist-put turn :ids nil))
      (agent-shell-fork-tree--ingest store '((sessionId . "none") (updatedAt . "1")) turns t "main"))
    (should (equal '(1 2) (aft-test-path store "none")))
    (aft-test-add store "main" '("alpha" "beta" "gamma") "2" "reloaded-")
    (should (= 3 (length (aft-test-path store "main"))))))

(ert-deftest aft-test-text-boundaries-are-unambiguous ()
  (should-not (equal (agent-shell-fork-tree--fingerprint "ab" "c")
                     (agent-shell-fork-tree--fingerprint "a" "bc"))))

(ert-deftest aft-test-full-rebuild-asks-and-does-not-replace-cache-on-failure ()
  (let* ((source (generate-new-buffer " *aft-source*"))
         (agent-shell-fork-tree-cache-directory nil)
         (old (agent-shell-fork-tree--new-store "fixture" "/tmp"))
         (prompts 0) (scans 0))
    (unwind-protect
        (with-temp-buffer
          (agent-shell-fork-tree-view-mode)
          (setq agent-shell-fork-tree--source source agent-shell-fork-tree--focus "main" agent-shell-fork-tree--store old)
          (cl-letf (((symbol-function 'shell-maker-busy) (lambda () nil))
                    ((symbol-function 'y-or-n-p) (lambda (_) (cl-incf prompts) t))
                    ((symbol-function 'run-at-time) (lambda (_time _repeat fn &rest args) (apply fn args)))
                    ((symbol-function 'agent-shell-fork-tree--scan)
                     (lambda (_source store _focus full _progress finish)
                       (cl-incf scans)
                       (when full (should-not (eq store old)))
                       (funcall finish store "Read failed" nil)
                       #'ignore)))
            (agent-shell-fork-tree-rebuild)
            (should (eq old agent-shell-fork-tree--store))
            (should (= prompts 1)) (should (= scans 2))
            (should-not agent-shell-fork-tree--loading)))
      (kill-buffer source))))

(ert-deftest aft-test-full-rebuild-decline-retains-cache ()
  (let ((calls 0))
    (cl-letf (((symbol-function 'y-or-n-p) (lambda (_) nil))
              ((symbol-function 'agent-shell-fork-tree-rebuild) (lambda (&rest _) (cl-incf calls))))
      (agent-shell-fork-tree--offer-full (current-buffer) "Mismatch")
      (should (zerop calls)))))

(ert-deftest aft-test-long-history-renders-without-recursion ()
  (let ((store (agent-shell-fork-tree--new-store "fixture" "/tmp")))
    (aft-test-add store "main" (cl-loop for i below 1500 collect (format "turn %d" i)))
    (with-temp-buffer
      (agent-shell-fork-tree-view-mode)
      (setq agent-shell-fork-tree--store store agent-shell-fork-tree--focus "main" agent-shell-fork-tree--selected 1500)
      (agent-shell-fork-tree--render)
      (should (= 1500 (get-text-property (point) 'fork-tree-node))))))
